tosca_definitions_version: dell_1_0

description: >
  Blueprint creates a Windows Virtual Machine in vSphere environment and installs
  one or multiple instances of XMPro Stream Host on top of it using
  Ansible Playbooks.

imports:
  - dell/types/types.yaml
  # Infrastructure - vSphere VM
  - infrastructure/xmpro_stream_host/vsphere/inputs.yaml
  - tests/infrastructure/xmpro_stream_host/vsphere/blueprint.yaml
  # Application - XMPro Stream Host
  - application/stream_host/inputs.yaml
  - application/stream_host/inputs_common.yaml
  - tests/application/stream_host/blueprint.yaml
  # Outputs
  - application/stream_host/outputs.yaml

labels:
  csys-obj-type:
    values:
      - service
  target_environment:
    values:
      - vsphere
  vendor:
    values:
      - xmpro
  solution:
    values:
      - stream_host
  version:
    values:
      - "4.3.7.0"

blueprint_labels:
  env:
    values:
      - vsphere
