node_templates:

  subscription_manager_vm:
    type: dell.nodes.ServiceComponent
    properties:
      resource_config:
        blueprint:
          external_resource: true
          id: Windows_Virtual_Machine_for_vSphere
          revision_id: 3.1.0.1
        deployment:
          display_name:
            concat:
              - "SM-vm-"
              - { get_sys: [deployment, name] }
          auto_inc_suffix: true
          inputs:
            vsphere_secret_name:
              get_environment_capability: vcenter_credentials
            template_name:
              get_input: vm_template
            vm_name:
              get_input: sm_hostname
            vm_user_name:
              get_input: vm_user_name
            vm_password_secret_name:
              get_input: sm_vm_password_secret_name
            resource_pool_name:
              get_input: resource_pool_name
            vm_folder_name:
              get_input: vm_folder
            datastore_name:
              get_input: datastore_name
            allowed_esxi_hosts:
              get_input: sm_allowed_esxi_host
            vcpu:
              get_input: sm_vcpus
            memory_size:
              get_input: sm_memory_size
            os_disk_size:
              get_input: sm_os_disk_size
            disk_provisioning:
              get_input: disk_provisioning
            storage_disk_size:
              get_input: storage_disk_size
            disks_count:
              get_input: disks_count
            storage_disk_provisioning:
              get_input: storage_disk_provisioning
            networking:
              get_input: sm_network_mappings
            pci_devices:
              get_input: sm_pci_devices
            usb_devices:
              get_input: sm_usb_devices
            serial_ports:
              get_input: sm_serial_ports
            nics:
              get_input: sm_nics_device_list
    relationships:
      - type: dell.relationships.depends_on
        target: validate_secrets
