---
- name: Get Windows VM IP
  hosts: win
  gather_facts: false
  tasks:
    - name: Get the IP address
      ansible.windows.win_shell: |
        $tapInterfaceMAC = "{{ tap_nic_mac }}".ToUpper() -replace ":", "-"
        $interfaceAliases = Get-NetAdapter | Select-Object -ExpandProperty InterfaceAlias
        $firstInterfaceMAC = (Get-NetAdapter -InterfaceAlias $interfaceAliases[0]).MacAddress
        $correctInterfaceAlias = If ($firstInterfaceMAC -eq $tapInterfaceMAC) {$interfaceAliases[1]} else {$interfaceAliases[0]}
        $interfaceIndex = (Get-NetAdapter -Name $correctInterfaceAlias).ifIndex
        $ipAddress = (Get-NetIPAddress -InterfaceIndex $interfaceIndex -AddressFamily IPv4).IPAddress
        Write-Host "$ipAddress"
      register: ip_address

    - name: Create a directory
      ansible.builtin.file:
        path: /tmp/{{ node_instance_id }}
        state: directory
      delegate_to: localhost

    - name: Create a temp file with VM IP
      ansible.builtin.copy:
        content: "{{ ip_address.stdout }}"
        dest: /tmp/{{ node_instance_id }}/vm_ip.txt
      delegate_to: localhost
