---
- name: Install XMPro Application Designer IIS Website
  hosts: application_designer_vm
  become_method: runas
  become_user: "{{ vm_user_name | default('Administrator') }}"
  gather_facts: false
  roles:
  - role: extract_iis_zip
    vars:
      installation_dir: "{{ installation_dir }}"
      zip_filename: "{{ zip_filename }}"
      website_directory: "C:\\inetpub\\wwwroot"
      destination_path: "C:\\inetpub\\wwwroot"

  - role: set_env_variables
    vars:
      censor_sensitive_data: "{{ censor_sensitive_data }}"
      environment_variables:
        xmpro__appDesigner__encryptionKey: "$([Guid]::NewGuid().ToString())"
        xmpro__xmidentity__client__id: "{{ ad_product_id }}"
        xmpro__xmidentity__client__sharedkey: "{{ ad_product_key }}"
        xmpro__xmidentity__client__baseUrl: "https://{{ ad_hostname | lower }}/"
        xmpro__xmidentity__server__baseUrl: "https://{{ sm_hostname | lower }}/"
        xmpro__xmnotification__email__enable: "{{ smtp_enable }}"
        xmpro__xmnotification__email__smtpServer: "{{ smtp_server }}"
        xmpro__xmnotification__email__port: "{{ smtp_port }}"
        xmpro__xmnotification__email__userName: "{{ smtp_user }}"
        xmpro__xmnotification__email__password: "{{ smtp_password }}"
        xmpro__xmnotification__email__enableSsl: "{{ smtp_enable_ssl }}"
        xmpro__xmnotification__email__fromAddress: "{{ smtp_from_address }}"
        xmpro__xmnotification__email__useDefaultCredentials: "false"
        xmpro__xmnotification__email__webApplication: "true"
        xmpro__xmnotification__email__templateFolder: "Templates"
        xmpro__data__connectionString:
          "Server=tcp:{{ sql_ip }};initial catalog=AD;persist security info=True;user id=XMProUser;password={{ xmpro_password }};"
        xmpro__xmsettings__data__connectionString:
          "Server=tcp:{{ sql_ip }};initial catalog=AD;persist security info=True;user id=XMProUser;password={{ xmpro_password }};"
        xmpro__xmsettings__adminRole: "Administrator"

  - role: restart_iis_service

  - role: start_process
    vars:
      filename: "{{ ms_dotnet_core_hosting_bundle_filename }}"
      arguments: "/repair /passive /norestart"
      installation_dir: "{{ installation_dir }}"

  - role: restart_iis_service

  - role: clean_up_environment
    vars:
      installation_dir: "{{ installation_dir }}"

  - role: reboot_machine
