inputs:

  sm_vm_user_name:
    type: string
    hidden: false
    allow_update: false
    display_label: Subscription Manager Deployment User
    description: |
      Name of the deployment user on the Virtual Machine.
      Cannot contain leading or trailing spaces.
    default: Administrator
    constraints:
    - pattern: ^(?!\s)(?!.*\s$).*$
      error_message: Cannot contain leading or trailing spaces.
    display:
      group: ned_sm
      index: 200

  sm_vm_password_secret_name:
    type: secret_key
    hidden: false
    allow_update: false
    display_label: Subscription Manager Virtual Machine Password Secret Name
    description: |
      Secret name containing the user password for
      the Windows Virtual Machine.
    constraints:
    - type: password
    display:
      group: ned_sm
      index: 205

  sm_hostname:
    type: string
    hidden: true
    allow_update: false
    display_label: Subscription Manager Hostname
    description: |
      Hostname of the Virtual Machine
      (an auto-generated suffix will also be added).
      Cannot contain characters other than:
      letters (a-z, A-Z), numbers (0-9), or hyphens (-).
      Can be up to 63 characters long.
    default:
      concat:
      - get_input: hostname_prefix
      - SM

  sm_vcpus:
    type: integer
    hidden: false
    allow_update: true
    display_label: Subscription Manager vCPUs
    description: |
      Number of virtual CPUs allocated to the Virtual Machine.
      See https://documentation.xmpro.com/resources/sizing-guideline
      for recommendations.
    default: 2
    constraints:
    - greater_or_equal: 2
    display:
      group: ned_sm
      index: 210

  sm_memory_size:
    type: string
    hidden: false
    allow_update: true
    display_label: Subscription Manager Memory Size
    description: |
      Memory size with unit [KB,MB,GB,TB,PB,EB,ZB,YB].
      See https://documentation.xmpro.com/resources/sizing-guideline
      for recommendations.
    default: 8GB
    constraints:
    - pattern: \d+(\.\d+)?(KB|MB|GB|TB|PB|EB|ZB|YB)
      error_message: |
        Incorrect format.
        Memory size must be followed by unit [KB,MB,GB,TB,PB,EB,ZB,YB].
        Example: 4GB
    display:
      group: ned_sm
      index: 215

  sm_os_disk_size:
    type: string
    hidden: false
    allow_update: true
    display_label: Subscription Manager OS Disk Size
    description: |
      Storage size with unit [KB,MB,GB,TB,PB,EB,ZB,YB].
      See https://documentation.xmpro.com/resources/sizing-guideline
      for recommendations.
    default: 40GB
    constraints:
    - pattern: \d+(\.\d+)?(KB|MB|GB|TB|PB|EB|ZB|YB)
      error_message: |
        Incorrect format.
        Disk size must be followed by unit [KB,MB,GB,TB,PB,EB,ZB,YB].
        Example: 50GB
    display:
      group: ned_sm
      index: 220

  sm_disk:
    type: string
    hidden: false
    allow_update: false
    display_label: Subscription Manager Endpoint Datastore Path
    description: |
      Deployment datastore path on target endpoint.
      Available datastores can be retrieved from the endpoint screen.
    constraints:
    - valid_values:
        jmespath:
        - extra.hw_core.storage.dataStoreOrVolumes[?((((type=='SSD'||type=='HDD')&&name.contains(@,'DataStore'))||(shared&&name=='/Shared_DataStore'))&&status=='ONLINE')].mountPath
        - get_inventory:
            get_environment_capability: ece_service_tag
    display:
      group: ned_sm
      index: 225

  sm_static_ip:
    type: string
    hidden: false
    exclusive_with: dhcp
    allow_update: false
    display_label: Subscription Manager Static IP and Mask Suffix
    description: |
      IP address and suffix. Example: 172.16.0.1/16.
      Only required for static IP deployments, not for DHCP.
    required: true
    display:
      group: ned_sm
      index: 230
    constraints:
    - pattern: ^(?:((25[0-5]|2[0-4]\d|1\d\d|\d{1,2})(\.(25[0-5]|2[0-4]\d|1\d\d|\d{1,2})){3})\/(3[0-2]|[12]?\d)|)$
      error_message: |
        Invalid format for IP Address in CIDR format.
        Example: 172.16.0.1/16

  sm_dns:
    type: list
    item_type: string
    hidden: true
    exclusive_with: dhcp
    allow_update: false
    display_label: Subscription Manager DNS Servers
    description: List of DNS servers addresses.
    required: true
    default:
      get_input: dns

  sm_gateway:
    type: string
    hidden: true
    exclusive_with: dhcp
    allow_update: false
    display_label: Subscription Manager Gateway IP Address
    description: IP Address of the Network Gateway.
    required: true
    default:
      get_input: gateway

  sm_usb:
    type: list
    item_type: string
    hidden: true
    allow_update: false
    display_label: Subscription Manager USB Devices List
    description: |
      A list of USB logical names to pass through to the Virtual Machine.
      Valid values are "USB-1" to "USB-10"
      Please make sure to select the USB port where USB device is connected.
    required: false
    constraints:
    - valid_values:
        jmespath:
        - extra.hw_core.usbDevice[*].logicalName
        - get_inventory:
            get_environment_capability: ece_service_tag

  sm_serial_port:
    type: list
    item_type: string
    hidden: true
    allow_update: false
    display_label: Subscription Manager Serial Port
    description: |
      Serial port passthrough.
      Please make sure to select the port where required device is connected.
      Example:
        - {"port": "COM-1"}
        - {"port": "COM-2"}
    required: false
    constraints:
    - valid_values:
        jmespath:
        - '[extra.hw_core.serialPorts[*].{"port":logicalName,"mode":`RS-232`}[*].values(@).join(`_`,@)[],extra.hw_core.serialPorts[*].{"port":logicalName,"mode":`RS-422`}[*].values(@).join(`_`,@)[],extra.hw_core.serialPorts[*].{"port":logicalName,"mode":`RS-485`}[*].values(@).join(`_`,@)[]][]'
        - get_inventory:
            get_environment_capability: ece_service_tag

  sm_gpu_passthrough:
    type: list
    item_type: string
    hidden: true
    allow_update: false
    display_label: Subscription Manager GPU Passthrough
    description: |
      A list of GPU logical names.
      Please make sure to select the GPU that is currently available in your
      Endpoint. A list of GPU logical names available for your endpoint can
      be found in the NativeEdge UI under Endpoints / Hardware / Peripherals
    required: false
    constraints:
    - valid_values:
        jmespath:
        - extra.hw_core.pciDevice[?deviceType=='GPU'].logicalName
        - get_inventory:
            get_environment_capability: ece_service_tag

  sm_video:
    type: list
    item_type: string
    hidden: true
    allow_update: false
    display_label: Subscription Manager Video Passthrough
    description: |
      Video passthrough. A list of Video logical names (string).
      E.g. ['onboarded-controller']
    required: false
    constraints:
    - valid_values:
        jmespath:
        - extra.hw_core.video[*].logicalName
        - get_inventory:
            get_environment_capability: ece_service_tag
