---
- name: Check if the Installation Directory already exists
  ansible.windows.win_shell:
    Test-Path -Path "{{ installation_dir }}"
  register: directory_exists

- name: Remove the Installation Directory if it exists
  ansible.windows.win_shell:
    Remove-Item -Path "{{ installation_dir }}" -Recurse -Force
  become: true
  when: "'True' in directory_exists.stdout"

- name: Create Installation Directory
  ansible.windows.win_file:
    path: "{{ installation_dir }}"
    state: directory
  become: true
